Line indent text annotation app
reflex-dev/templates pull request #7
Opened 2024-06-15 16:35 UTC by LineIndent

This app base foundation - user's create a category (label) and they can highlight a text segment. We can add more details

2024-06-25 00:17 UTC, Alek99 requested changes

2024-06-25 00:17 UTC, Alek99 commented on text_annotation/app2/components/annotation.py
For this lets stick to radix components except the accordion that can be chakra

2024-07-08 16:35 UTC, Alek99 commented
The rx.upload here should use the accept prop to filter out only valid file types, I tried to pass in a txt file but got an error.

2024-07-18 01:46 UTC, picklelo reviewed
This is working nicely for me! I'm thinking we should move this to the reflex-examples repo as it may fit better as an example app than a starter template.

2024-07-18 16:26 UTC, LineIndent commented
Sounds good - let me know what you guys decide so I can make a new PR in the reflex-examples repo.

2024-07-18 20:25 UTC, picklelo commented
@LineIndent I think go ahead and add this in the examples repo and we can merge it

2024-07-18 21:10 UTC, LineIndent commented
Great 👍🏼 I made the PR and I'll close this one

2024-07-18 21:10 UTC, closed without merging